### PR TITLE
Configurable time

### PR DESCRIPTION
**Pull request by mfine**
Take time in epoch form as a parameter.

### CODE REVIEW

**Comment by silverjam** [comment]
Should we update https://github.com/swift-nav/ntripping too?  Do we need two versions of this tool?

**Comment by silverjam** [comment]
I ported this to Rust so it'd be easier to build and fit with our other tools, but if we're going to keep ignoring the Rust version and updating this one instead then we should just delete it, there's no point in having two of the same tool.

**Comment by silverjam** [comment]
Rust version builds on Windows too FWIW

**Comment by mfine** [comment]
> Do we need two versions of this tool?

This is reference NTRIP code that we've made available to users on how to simply do a NTRIP client.

**Pull request merged**
